DROP TABLES IF EXISTS books;

CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL
    cover_image TEXT NOT NULL
    rating BIGINT
    price BIGINT
    in_stock BOOLEAN
);

